/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buddy;

import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author User
 */
public class LTADisplayMenu extends javax.swing.JFrame {

    /**
     * Creates new form LTADisplayMenu
     */
    private Service currentService;
    
    public LTADisplayMenu() {
        initComponents();
        busInfoLabel.setOpaque(true);
        
        
    }
    
    public void PopulateBusList()
    {
        jDisplayList.removeAll();
        //jDisplayList = LTAManager.ServiceHashMap;
        DefaultListModel listModel = new DefaultListModel();
        
        
        for(String s : LTAManager.ServiceHashMap.keySet())
        {   
           listModel.addElement(s);
        }
        
        jDisplayList.setModel(listModel);
        jDisplayList.setSelectedIndex(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDisplayList = new javax.swing.JList();
        busInfoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        serviceNumberLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        routeTab = new javax.swing.JTabbedPane();
        inspectButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 204));
        setForeground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        jDisplayList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jDisplayList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jDisplayListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jDisplayList);

        busInfoLabel.setBackground(new java.awt.Color(204, 0, 153));
        busInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        busInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        busInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busInfoLabel.setText("Bus Information");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Service Number:");

        serviceNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Routes:");

        inspectButton.setText("View");
        inspectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspectButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel3.setText("* Distance measured in km *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(busInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inspectButton))
                                        .addComponent(routeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 7, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(serviceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serviceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(routeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inspectButton)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jListMouseDoubleClicked(java.awt.event.MouseEvent evt) {                                            
    JList list = (JList)evt.getSource();
    if (evt.getClickCount() == 2) {
        int index = list.locationToIndex(evt.getPoint());  
        Inspect();
    }
}
    
    private void jDisplayListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jDisplayListValueChanged
        // TODO add your handling code here:
        currentService = LTAManager.ServiceHashMap.get(jDisplayList.getSelectedValue());
        
        
        if(currentService != null)
        {
            routeTab.removeAll(); 
            serviceNumberLabel.setText(currentService.GetServiceCode());
            
            
            for( int i = 0; i < currentService.GetRouteList().size(); i++)
            {
                DefaultListModel listModel = new DefaultListModel();
                
                
                for(StationRouteInfo sri : currentService.GetRoute(i).GetStationsToDistRef())
                {
                    listModel.addElement(sri);    
                }        
                JList currentJList = new JList();
                currentJList.setModel(listModel);

                currentJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseDoubleClicked(evt);
            }
        });
                
                
                
                currentJList.setCellRenderer(new DefaultListCellRenderer()
                {
                    @Override
                    public Component getListCellRendererComponent(JList<?> list,
                                                   Object value,
                                                   int index,
                                                   boolean isSelected,
                                                   boolean cellHasFocus)
                    {
                        Component renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                        if (renderer instanceof JLabel && value instanceof StationRouteInfo)
                        {
                            StationRouteInfo currentSRI = (StationRouteInfo)value;
                            String text = currentSRI.getDistFromStart() + "  ------ " +  
                                    LTAManager.GetGenericStation(currentSRI.getStationCode()).GetName();
                            
                            
                            ((JLabel)renderer).setText(text);
                        }
                        return renderer;
                    }
                    //@Override
                    //public Component getListCellRendererComponent(JList<?>)
                }
                );
                
                // Add a new tab
                routeTab.add("" + (i+1) , new JScrollPane(currentJList));
            }
            
        }
        
    }//GEN-LAST:event_jDisplayListValueChanged

    private void inspectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspectButtonActionPerformed
        // TODO add your handling code here:    
        Inspect();
      
    }//GEN-LAST:event_inspectButtonActionPerformed

    private void Inspect()
    {
        JScrollPane selectedScrollPane = (JScrollPane)routeTab.getSelectedComponent();
        JList selectedList = (JList)selectedScrollPane.getViewport().getComponent(0);
        
        StationRouteInfo selectedSRI = (StationRouteInfo)selectedList.getSelectedValue();
        if(selectedSRI != null)
        {
            LTAStopMenu stopMenu = new LTAStopMenu(LTAManager.GetGenericStation(selectedSRI.getStationCode()));
            stopMenu.setVisible(true);
        }
        else
            System.out.println("nothing to view");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LTADisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LTADisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LTADisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LTADisplayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LTADisplayMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busInfoLabel;
    private javax.swing.JButton inspectButton;
    private javax.swing.JList jDisplayList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane routeTab;
    private javax.swing.JLabel serviceNumberLabel;
    // End of variables declaration//GEN-END:variables
}
