/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buddy;

import javax.swing.DefaultListModel;

/**
 *
 * @author User
 */
public class LTAStopMenu extends javax.swing.JFrame {

    /**
     * Creates new form LTAStopMenu
     * @param gs
     */
    public LTAStopMenu(GenericStation gs) {
        initComponents();
        stationNameLabel.setOpaque(true);
        stationNameLabel.setText("<html>" + gs.GetName()+ "<br><div style = 'text-align : center;'>" + gs.GetID() + "</div></html>");DefaultListModel listModel = new DefaultListModel();
        PopulateServiceList(gs);
        
    }
    
    private void PopulateServiceList(GenericStation gs)
    {
        DefaultListModel listModel = new DefaultListModel();
        
        for(StationRouteInfo sri : gs.GetStationRouteInfoList())
        {
            if(sri.getStationCode().equals(gs.GetID()) && !listModel.contains(sri.getServiceNo()))
                listModel.addElement(sri.getServiceNo());
        }
        
        
        jList1.setModel(listModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stationNameLabel = new javax.swing.JLabel();
        busIcon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        mrtIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        stationNameLabel.setBackground(new java.awt.Color(51, 204, 255));
        stationNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stationNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        stationNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stationNameLabel.setText("Station Name");

        busIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LTAResources/smallbusIcon.png"))); // NOI18N

        jList1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stationNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(busIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrtIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stationNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mrtIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busIcon;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mrtIcon;
    private javax.swing.JLabel stationNameLabel;
    // End of variables declaration//GEN-END:variables
}
