/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buddy;

/**
 *
 * @author User
 */
public class LTAStopMenu extends javax.swing.JFrame {

    /**
     * Creates new form LTAStopMenu
     * @param gs
     */
    public LTAStopMenu(GenericStation gs) {
        initComponents();
        stationNameLabel.setOpaque(true);
        stationNameLabel.setText(gs.GetName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stationNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stationNameLabel.setBackground(new java.awt.Color(51, 204, 255));
        stationNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stationNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stationNameLabel.setText("Station Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stationNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stationNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel stationNameLabel;
    // End of variables declaration//GEN-END:variables
}
